---
  language: python
  python:
    - "2.7"
#    - "3.3"
#    - "3.4"
  # command to install dependencies
  services:
    - mysql
  before_install:
    - 'mysql -e "create database if not exists downstream;" -u root'
  install:
    - "pip install ."
    - "pip install git+https://github.com/Storj/heartbeat.git@master"

  # command to run tests
  script: nosetests -v tests/